---
- hosts: all
  become: true
#  remote_user: root
#  vars_files:
#    - vars/default.yml
#    - secret

  tasks:
    - name: update cache
      apt:
        update_cache: yes

    - name: Update all installed packages
      apt:
        name: "*"
        state: latest

    - name: Make sure NTP service is running
      systemd:
        state: started
        name: systemd-timesyncd

    - name: Make sure we have a 'sudo' group
      group:
        name: sudo
        state: present

#    - name: Create a user with sudo privileges
#      user:
#        name: "{{ create_user }}"
#        state: present
#        groups: sudo
#        append: true
#        create_home: true
#        shell: /bin/bash
#        password: "{{ password | password_hash('sha512', password_salt) }}"
#        update_password: on_create

#    - name: Set authorized key for remote user
#      authorized_key:
#        user: "{{ create_user }}"
#        state: present
#        key: "{{ copy_local_key }}"

    - name: Disable remote login for root
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^PermitRootLogin yes'
        line: 'PermitRootLogin no'

    - name: Change the SSH port
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#Port 22'
        line: 'Port "{{ ssh_port }}"'

    - name: Disable ipv6 on UFW
      replace:
        path: /etc/default/ufw
        regexp: "IPV6=yes"
        replace: "IPV6=no"

#    - name: Allow UFW ports
#      community.general.ufw:
#        rule: allow
#        port: "{{ ssh_port }}"

#    - name: Enable UFW Outgoing Allow
#      community.general.ufw:
#        state: enabled
#        direction: outgoing
#        policy: allow

#    - name: Enable UFW Incoming Deny
#      community.general.ufw:
#        state: enabled
#        direction: incoming
#        policy: deny

#    - name: Brute-force attempt protection for SSH
#      community.general.ufw:
#        rule: limit
#        port: "{{ ssh_port }}"
#        proto: tcp

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    - name: Restart the SSH daemon
      systemd:
        state: restarted
        name: ssh

    - name: Reboot all hosts
      reboot:
