---
- hosts: all
  become: true
  vars:
    project: traefik
  tasks:
    - name: Create a network
      community.docker.docker_network:
        name: proxy
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /dockers/{{ project }}
        state: directory
        mode: '0755'
    - name: copy Docker Compose files
      copy:
        src: /etc/semaphore/dockers/{{ project }}/{{ item }}
        dest: /dockers/{{ project }}/{{ item }}
        owner: root
        group: root
        mode: u=rw, g=rw, o=r
       with_items:
        - docker-compose.yml
        - traefik.yml
        - config.yml
#    - name: deploy Docker Compose stack
#      community.docker.docker_compose:
#        project_src: /dockers/{{ project }}/{{ item }}
#    - name: Show results
#      ansible.builtin.debug:
#        var: output
        
