---
- hosts: all
  become: true
  vars:
    project: traefik
  tasks:
    - name: Create a network
      community.docker.docker_network:
        name: proxy
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /dockers/{{ project }}
        state: directory
        mode: '0755'
    - name: copy Docker Compose files
      copy:
        src: /etc/semaphore/dockers/{{ project }}/{{ item }}
        dest: /dockers/{{ project }}/
        mode: '755'
      with_items:
        - docker-compose.yml
        - traefik.yml
        - config.yml
    - name: Replace old hostname with new hostname (requires Ansible >= 2.4)
      ansible.builtin.replace:
        path: /dockers/{{ project }}/config.yml
        regexp: "##domain##"
        replace: "{{ domain }}"
#    - name: deploy Docker Compose stack
#      community.docker.docker_compose:
#        project_src: /dockers/{{ project }}/{{ item }}
#    - name: Show results
#      ansible.builtin.debug:
#        var: output
        
